name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3
      uses: actions/setup-python@v2
      with:
        python-version: 3

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: run test
      run: python3 test.py
